/**
 * Seed data for initial development and demo purposes.
 * In production, this will be replaced by Supabase data seeded from Google Places scraping.
 */

import { Contractor, City, State } from '@/types';

export const SEED_CONTRACTORS: Contractor[] = [
  {
    id: '1',
    name: 'Rocky Mountain Fence Co',
    slug: 'rocky-mountain-fence-co-denver',
    phone: '3035551234',
    email: 'info@rockymountainfence.com',
    website: 'https://rockymountainfence.com',
    description: 'Denver\'s premier fence installation company. Family-owned since 2005, we specialize in wood privacy fences, vinyl fencing, and custom gates. Free estimates and competitive pricing.',
    address: '1234 W Colfax Ave',
    city: 'Denver',
    state: 'CO',
    zip: '80204',
    lat: 39.7392,
    lng: -104.9903,
    rating: 4.8,
    reviewCount: 127,
    services: ['installation', 'repair', 'gates', 'residential', 'commercial'],
    materials: ['wood', 'vinyl', 'chain-link', 'aluminum'],
    serviceRadius: 30,
    yearsInBusiness: 21,
    licensed: true,
    insured: true,
    freeEstimates: true,
    photos: [],
    featured: true,
    verified: true,
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: '2',
    name: 'Mile High Fencing',
    slug: 'mile-high-fencing-aurora',
    phone: '3035555678',
    description: 'Serving the Aurora and East Denver metro area with quality fence installation and repair. We handle everything from chain link to ornamental iron.',
    address: '5678 E Colfax Ave',
    city: 'Aurora',
    state: 'CO',
    zip: '80010',
    lat: 39.7294,
    lng: -104.8319,
    rating: 4.5,
    reviewCount: 89,
    services: ['installation', 'repair', 'replacement', 'residential'],
    materials: ['wood', 'chain-link', 'wrought-iron'],
    serviceRadius: 25,
    yearsInBusiness: 12,
    licensed: true,
    insured: true,
    freeEstimates: true,
    photos: [],
    featured: false,
    verified: true,
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: '3',
    name: 'Lone Star Fence Pros',
    slug: 'lone-star-fence-pros-dallas',
    phone: '2145551234',
    website: 'https://lonestarfencepros.com',
    description: 'Dallas-Fort Worth\'s top-rated fence contractor. Specializing in cedar wood fences, iron fencing, and automatic gate systems. Licensed, bonded, and insured.',
    address: '789 Main St',
    city: 'Dallas',
    state: 'TX',
    zip: '75201',
    lat: 32.7767,
    lng: -96.7970,
    rating: 4.9,
    reviewCount: 203,
    services: ['installation', 'repair', 'gates', 'residential', 'commercial'],
    materials: ['wood', 'wrought-iron', 'aluminum', 'chain-link'],
    serviceRadius: 40,
    yearsInBusiness: 18,
    licensed: true,
    insured: true,
    freeEstimates: true,
    photos: [],
    featured: true,
    verified: true,
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: '4',
    name: 'Sunshine State Fencing',
    slug: 'sunshine-state-fencing-miami',
    phone: '3055559876',
    description: 'South Florida\'s trusted fence company. Hurricane-rated fencing, aluminum pool enclosures, and PVC/vinyl privacy fences built to last in the Florida climate.',
    address: '456 Ocean Dr',
    city: 'Miami',
    state: 'FL',
    zip: '33139',
    lat: 25.7617,
    lng: -80.1918,
    rating: 4.6,
    reviewCount: 156,
    services: ['installation', 'repair', 'replacement', 'residential', 'commercial'],
    materials: ['aluminum', 'vinyl', 'chain-link', 'wrought-iron'],
    serviceRadius: 35,
    yearsInBusiness: 15,
    licensed: true,
    insured: true,
    freeEstimates: true,
    photos: [],
    featured: false,
    verified: true,
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: '5',
    name: 'Pacific Fence & Wire',
    slug: 'pacific-fence-wire-portland',
    phone: '5035554321',
    website: 'https://pacificfencewire.com',
    description: 'Portland\'s oldest fence company, est. 1998. Cedar, chain link, and ornamental iron fencing. We also offer deck and patio construction.',
    address: '321 NW 23rd Ave',
    city: 'Portland',
    state: 'OR',
    zip: '97210',
    lat: 45.5152,
    lng: -122.6784,
    rating: 4.7,
    reviewCount: 94,
    services: ['installation', 'repair', 'staining', 'gates', 'residential'],
    materials: ['wood', 'chain-link', 'wrought-iron', 'composite'],
    serviceRadius: 30,
    yearsInBusiness: 28,
    licensed: true,
    insured: true,
    freeEstimates: true,
    photos: [],
    featured: true,
    verified: true,
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: '6',
    name: 'Arvada Fence Masters',
    slug: 'arvada-fence-masters-arvada',
    phone: '3035559999',
    description: 'Your local Arvada fence experts. We build beautiful wood and vinyl fences for homes throughout Jefferson County. Veteran-owned.',
    address: '100 Olde Wadsworth Blvd',
    city: 'Arvada',
    state: 'CO',
    zip: '80002',
    lat: 39.8028,
    lng: -105.0875,
    rating: 4.9,
    reviewCount: 67,
    services: ['installation', 'repair', 'staining', 'residential'],
    materials: ['wood', 'vinyl', 'composite'],
    serviceRadius: 20,
    yearsInBusiness: 8,
    licensed: true,
    insured: true,
    freeEstimates: true,
    photos: [],
    featured: false,
    verified: true,
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
];

export const SEED_CITIES: City[] = [
  { name: 'Denver', state: 'Colorado', stateCode: 'CO', slug: 'denver-co', lat: 39.7392, lng: -104.9903, population: 715522, contractorCount: 45 },
  { name: 'Aurora', state: 'Colorado', stateCode: 'CO', slug: 'aurora-co', lat: 39.7294, lng: -104.8319, population: 386261, contractorCount: 22 },
  { name: 'Arvada', state: 'Colorado', stateCode: 'CO', slug: 'arvada-co', lat: 39.8028, lng: -105.0875, population: 124402, contractorCount: 12 },
  { name: 'Dallas', state: 'Texas', stateCode: 'TX', slug: 'dallas-tx', lat: 32.7767, lng: -96.7970, population: 1304379, contractorCount: 78 },
  { name: 'Houston', state: 'Texas', stateCode: 'TX', slug: 'houston-tx', lat: 29.7604, lng: -95.3698, population: 2304580, contractorCount: 95 },
  { name: 'Miami', state: 'Florida', stateCode: 'FL', slug: 'miami-fl', lat: 25.7617, lng: -80.1918, population: 442241, contractorCount: 38 },
  { name: 'Orlando', state: 'Florida', stateCode: 'FL', slug: 'orlando-fl', lat: 28.5383, lng: -81.3792, population: 307573, contractorCount: 28 },
  { name: 'Portland', state: 'Oregon', stateCode: 'OR', slug: 'portland-or', lat: 45.5152, lng: -122.6784, population: 652503, contractorCount: 32 },
  { name: 'Phoenix', state: 'Arizona', stateCode: 'AZ', slug: 'phoenix-az', lat: 33.4484, lng: -112.0740, population: 1608139, contractorCount: 65 },
  { name: 'Atlanta', state: 'Georgia', stateCode: 'GA', slug: 'atlanta-ga', lat: 33.7490, lng: -84.3880, population: 498715, contractorCount: 42 },
  { name: 'Chicago', state: 'Illinois', stateCode: 'IL', slug: 'chicago-il', lat: 41.8781, lng: -87.6298, population: 2693976, contractorCount: 88 },
  { name: 'Los Angeles', state: 'California', stateCode: 'CA', slug: 'los-angeles-ca', lat: 34.0522, lng: -118.2437, population: 3979576, contractorCount: 110 },
  { name: 'San Antonio', state: 'Texas', stateCode: 'TX', slug: 'san-antonio-tx', lat: 29.4241, lng: -98.4936, population: 1547253, contractorCount: 55 },
  { name: 'Nashville', state: 'Tennessee', stateCode: 'TN', slug: 'nashville-tn', lat: 36.1627, lng: -86.7816, population: 689447, contractorCount: 35 },
  { name: 'Charlotte', state: 'North Carolina', stateCode: 'NC', slug: 'charlotte-nc', lat: 35.2271, lng: -80.8431, population: 874579, contractorCount: 40 },
];

export const MAJOR_STATES: State[] = [
  { name: 'Colorado', code: 'CO', slug: 'colorado', cities: SEED_CITIES.filter(c => c.stateCode === 'CO'), contractorCount: 120 },
  { name: 'Texas', code: 'TX', slug: 'texas', cities: SEED_CITIES.filter(c => c.stateCode === 'TX'), contractorCount: 450 },
  { name: 'Florida', code: 'FL', slug: 'florida', cities: SEED_CITIES.filter(c => c.stateCode === 'FL'), contractorCount: 320 },
  { name: 'California', code: 'CA', slug: 'california', cities: SEED_CITIES.filter(c => c.stateCode === 'CA'), contractorCount: 520 },
  { name: 'Oregon', code: 'OR', slug: 'oregon', cities: SEED_CITIES.filter(c => c.stateCode === 'OR'), contractorCount: 85 },
  { name: 'Arizona', code: 'AZ', slug: 'arizona', cities: SEED_CITIES.filter(c => c.stateCode === 'AZ'), contractorCount: 180 },
  { name: 'Georgia', code: 'GA', slug: 'georgia', cities: SEED_CITIES.filter(c => c.stateCode === 'GA'), contractorCount: 200 },
  { name: 'Illinois', code: 'IL', slug: 'illinois', cities: SEED_CITIES.filter(c => c.stateCode === 'IL'), contractorCount: 280 },
  { name: 'Tennessee', code: 'TN', slug: 'tennessee', cities: SEED_CITIES.filter(c => c.stateCode === 'TN'), contractorCount: 150 },
  { name: 'North Carolina', code: 'NC', slug: 'north-carolina', cities: SEED_CITIES.filter(c => c.stateCode === 'NC'), contractorCount: 190 },
];
